export const siteQuestions: any = {

    "Collectorate HK": [
        {
            id: "matrixAttendance",  // 🔥 ADD THIS
            question: "Is attendance being recorded on matrix track?",
            type: "yesno",
            requireReasonOnNo: true
        },
        { question: "Cleanliness and maintenance of the entry and parking area", type: "rating" },
        { question: "Cleanliness and maintenance of the main garden", type: "rating" },
        { question: "Cleanliness and maintenance of the DM office and attached washroom", type: "rating" },
        { question: "Cleanliness and maintenance of the ADM office", type: "rating" },
        { question: "Cleanliness and maintenance of the SDM office", type: "rating" },
        { question: "Cleanliness and maintenance of the Jan Sunwai room", type: "rating" },
        { question: "Cleanliness and maintenance of the board room", type: "rating" },
        { question: "Cleanliness and maintenance of the water cooler area", type: "rating" },
        { question: "Proper segregation and cleanliness of the waste dumping site", type: "rating" },
        { question: "Cleanliness and maintenance of the water tank", type: "rating" },
        { question: "Hygiene and cleanliness of the canteen area", type: "rating" },
        { question: "Manpower discipline and attendance", type: "rating" },
        { question: "Adequacy of manpower at the site", type: "rating" },
        { question: "Any urgent issue observed at the site", type: "yesno", requireReasonOnYes: true }

    ],

    "Pithampur Muncipal Corporation": [
        {
            id: "matrixAttendance",  // 🔥 ADD THIS
            question: "Is attendance being recorded on matrix track?",
            type: "yesno"
        },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],

    "Hotel EDEN": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Crystal IT Park": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }
    ],

    "HMS  Office": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Solaris Office": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Ida Pro": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "khajrana Ganesh Mandir": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Ida Indore": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],

    "Daly College (Consulting)": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MPIDC Gwalior ": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MPSEDC Bhopal": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Dewas Muncipal Corporation": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],


    "ISBT Raipur": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],


    "Daly college": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MRF Kabir khedi": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "ICICI Banks": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Hotel Sundervan": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MD  House": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "county walk": [
        { question: "Is attendance being recorded on matrix track?", type: "yesno", requireReasonOnNo: true },
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
}
