export const siteQuestions: any = {

    "Collector Office": [

        { question: "Cleanliness and maintenance of the entry and parking area", type: "rating" },
        { question: "Cleanliness and maintenance of the main garden", type: "rating" },
        { question: "Cleanliness and maintenance of the DM office and attached washroom", type: "rating" },
        { question: "Cleanliness and maintenance of the ADM office", type: "rating" },
        { question: "Cleanliness and maintenance of the SDM office", type: "rating" },
        { question: "Cleanliness and maintenance of the Jan Sunwai room", type: "rating" },
        { question: "Cleanliness and maintenance of the board room", type: "rating" },
        { question: "Cleanliness and maintenance of the water cooler area", type: "rating" },
        { question: "Proper segregation and cleanliness of the waste dumping site", type: "rating" },
        { question: "Cleanliness and maintenance of the water tank", type: "rating" },
        { question: "Hygiene and cleanliness of the canteen area", type: "rating" },
        { question: "Manpower discipline and attendance", type: "rating" },
        { question: "Adequacy of manpower at the site", type: "rating" },
        { question: "Any urgent issue observed at the site", type: "yesno", requireReasonOnYes: true }

    ],
    "MPSEDC": [
        { question: "Cleanliness and maintenance of the outer area", type: "rating" },
        { question: "Cleanliness and maintenance of the reception area", type: "rating" },
        { question: "Cleanliness and maintenance of the ground floor washrooms", type: "rating" },
        { question: "Cleanliness and maintenance of the first floor washrooms", type: "rating" },
        { question: "Cleanliness and maintenance of the second floor washrooms", type: "rating" },
        { question: "Cleanliness and maintenance of the Project Director's office (First Floor)", type: "rating" },
        { question: "Cleanliness of the meeting room (First Floor) and availability of room freshener", type: "rating" },
        { question: "Cleanliness of the meeting room (Second Floor) and availability of room freshener", type: "rating" },
        { question: "Cleanliness of the meeting room (Third Floor) and availability of room freshener", type: "rating" },
        { question: "Cleanliness and maintenance of the CGM office", type: "rating" },
        { question: "Cleanliness and maintenance of the coffee area (Second Floor)", type: "rating" },
        { question: "Cleanliness and maintenance of the coffee area (Third Floor)", type: "rating" },
        { question: "Any urgent issue observed at the site", type: "yesno", requireReasonOnYes: true }
    ],
    "Pitampur Municipal Corporation": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],

    "Hotel sunder ( EDN)": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Crystal IT Park": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }
    ],
    "Anik industry": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "HMS  Office": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Solaris Office": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Ida Pro": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "khajrana Ganesh Mandir": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Ida Indore": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],

    "Daly College (Consulting)": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MPIDC Gwalior ": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MPSEDC Bhopal": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Dewas Municipal Corporation": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MPSED Lift": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "22 Janni Surksha Yojana": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "ISBT Raipur": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "ADM House": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MPSEDC indore": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Daly college": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MRF Kabir khedi": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "ICICI Banks": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "Hotel Sundar van": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "MD  House": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
    "county walk": [
        { question: "Was attendance physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Was grooming and uniform checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was housekeeping checklist verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Were CCTV cameras checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Were fire safety systems inspected?", type: "yesno", requireReasonOnNo: true },
        { question: "Were electrical panels checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was plumbing leakage checked?", type: "yesno", requireReasonOnNo: true },
        { question: "Was material stock physically verified?", type: "yesno", requireReasonOnNo: true },
        { question: "Total sanctioned manpower for the site", type: "number" },
        { question: "Number of staff present today", type: "number" },
        { question: "Number of staff absent", type: "number" },
        { question: "Is manpower shortage affecting operations?", type: "yesno", requireReasonOnYes: true },
        { question: "Is replacement arranged?", type: "yesno", requireReasonOnNo: true },
        { id: "hiringRequest", question: "Is hiring request raised?", type: "yesno" },
        { question: "Is cleaning schedule followed?", type: "yesno", requireReasonOnNo: true },
        { question: "Are toilets cleaned as per frequency?", type: "yesno", requireReasonOnNo: true },
        { question: "Is garbage disposal done on time?", type: "yesno", requireReasonOnNo: true },
        { question: "Are machines functioning properly?", type: "yesno", requireReasonOnNo: true },
        { question: "Are all guards present?", type: "yesno", requireReasonOnNo: true },
        { question: "Is patrolling done as per schedule?", type: "yesno", requireReasonOnNo: true },
        { question: "Any electrical complaints received?", type: "yesno", requireReasonOnYes: true },
        { question: "Any plumbing leakage observed?", type: "yesno", requireReasonOnYes: true }

    ],
}
