export const sites = [
    "AARONE (Bonsai Site)",
    "AARONE (CountyWalk)",
    "AARONE (Countywalk EWS)",
    "AARONE (Countywalk Oasis)",
    "AARONE (Group Housing)",
    "AARONE (Oasis Club House)",
    "Crystal IT Park",
    "Daly College (DCM/DCBS)",
    "Daly College (HMS)",
    "Dewas Municipal Corporation",
    "Dist. Collector",
    "HEAD OFFICE",
    "HOTEL EDEN",
    "HOTEL SUNDERVAN",
    "ICICI BANK",
    "IDA MANPOWER",
    "IDA PRO",
    "ISBT Raipur",
    "KHAJRANA GANESH TEMPLE",
    "MD HOUSE",
    "MGM DATA OPERATORS",
    "MPIDC Gwalior",
    "MPSEDC Bhopal",
    "MRF Kabit Khedi",
    "Pithampur Muncipal Corporation",
    "RAJKUMAR",
    "ROHAN SIR HOUSEKEEPER SATHEE SIR SE",
    "Ruchi Reality",

]