export const sites = [
    "Aarone",
    "Crystal IT Park",
    "Daly College",
    "Dewas Municipal Corporation",
    "Dist. Collector",
    "IDA",
    "ISBT Raipur",
    "MGM",
    "MPIDC Gwalior",
    "MPSEDC Bhopal",
    "Pithampur Muncipal Corporation",
    "Ruchi Reality",
    "Shri Ganpati Khajrana",
]